### PR TITLE
lua.hpp from luajit requires luajiit.h.

### PR DESCRIPTION
**Pull request by xpol**
This make lua module written in c++ have `#include "lua.hpp"` can compile.

### CODE REVIEW

**Comment by ignacio** [comment]
Strange... it is failing. Your change is correct but AppVeyor spits some error about a label not being found. I tested your changes locally and they're ok. I'll retry the job in a while and see what happens.

**Comment by ignacio** [comment]
I think it was a hiccup of AppVeyor. The code is fine.

**Comment by ignacio** [comment]
Well. Removing luajit.h from the list of files worked. Adding it back caused the build to fail.

Saw [this question on SO](http://stackoverflow.com/questions/232651/why-the-system-cannot-find-the-batch-label-specified-is-thrown-even-if-label-e) and checked the line endings. They were ok.
Added some empty lines in the middle of the script. It worked.

I should give another look at Powershell. This is embarrassing.

**Comment by xpol** [comment]
Shall we just:

```Batch
:: copy all headers begin with 'lua': lauxlib.h lua.h lua.hpp luaconf.h lualib.h luajit.h
copy "!lj_source_folder!\src\lua*.h*" "!lj_dest_folder!\include"
```

**Pull request merged**
