### PR TITLE
Install all Lua version in same root dir to simplify cache

### PR DESCRIPTION
**Pull request by moteus**

### CODE REVIEW

**Comment by ignacio** [comment]
Ok. What do you think of having the platform in there too? For instance:

~~~~
c:\lua\x86\5.2.4
c:\lua\x64\5.2.4
~~~~

This way, I can ran the full matrix locally.

**Comment by moteus** [comment]
I have no objection.

But really I think we need 2 separate config to debug and to release because appveyor really slow.
So in debug mode (on every commit we run only few jobs) and on release we run all matrix and upload releases on github. There exist example in deploy docs.

PS. Right now I have problem with pushing to github because DDoS.

**Comment by moteus** [comment]
Also you can put LuaRocks to %LUA_DIR%
```cmd
set LUAROCKS_INSTALL=%LUA_DIR%\LuaRocks
set LR_SYSTREE=%LUAROCKS_INSTALL%\systree

call install.bat /LUA %LUA_DIR% /Q /LV %LUA_SHORTV% /P "%LUAROCKS_INSTALL%" /TREE "%LR_SYSTREE%"
```

**Comment by ignacio** [comment]
Good. Merged this. I'll split the instalation dir by architecture and also put LuaRocks in there.

**Comment by ignacio** [comment]
I'd like to ellaborate a little bit on this:

> But really I think we need 2 separate config to debug and to release because appveyor really slow.
So in debug mode (on every commit we run only few jobs) and on release we run all matrix and upload releases on github. There exist example in deploy docs.

When you talk about debug and release, you are talking about regular development (debug) and run full tests and deploy artifacts (release), right?

I think that is best to left the full matrix enabled by default. If you need to develop and test using a single configuration you can work on a branch and edit appveyor.yaml to suit your needs (to clarify, by "you" I mean whoever ends up using this example scripts).

About pushing releases to Github, that would be the icing on the cake. Push the release to Github, deploy the rock on LuaRocks. We should continue this in a new issue, don't you think?

**Pull request merged**
